[lints.clippy]

[package]
name = "astry"
version = "26.8.0"
edition = "2024"
description = "astry the programming language"
repository = "https://github.com/Censera/astry"
readme = "README.md"
license = "Apache-License-2.0"
keywords = ["compiler", "language", "llvm"]
categories = ["command-line-utilities", "development-tools::compilers"]

[[bin]]
name = "astry"
path = "src/entry/main.rs"

[dependencies]
an-inkwell = "26"

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1
panic = "abort"
