[lints.clippy]

[package]
name = "astery"
version = "26.8.0"
edition = "2024"
description = "astery the programming language"
repository = "https://github.com/Censera/astery"
readme = "README.md"
license = "Apache-License-2.0"
keywords = ["compiler", "language", "llvm"]
categories = ["command-line-utilities", "development-tools::compilers"]

[[bin]]
name = "astery"
path = "src/cli/main.rs"

[dependencies]
an-inkwell = "26"

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1
panic = "abort"
